#!/usr/bin/env bash
#
# poll-repos.sh — Detect new commits on main for monitored repos via GitHub CLI.
#
# Designed to run on a cron schedule (e.g. every 15 minutes). When new commits
# are found, identifies which documentation files may need updating using the
# doc-map, then optionally triggers a deep drift check via livedocs + Sourcegraph MCP.
#
# Usage:
#   ./poll-repos.sh              Check for changes, report affected docs
#   ./poll-repos.sh --deep       Also run livedocs extraction + structural drift analysis
#   ./poll-repos.sh --semantic   Also run cross-repo semantic check (validates content accuracy)
#   ./poll-repos.sh --status     Show current state (last-seen SHAs)
#   ./poll-repos.sh --reset      Clear state (next run treats everything as new)
#
# Cron example (every 15 minutes):
#   */15 * * * * cd /path/to/gascity_livedocs && ./poll-repos.sh --deep >> logs/poll.log 2>&1
#
# Notifications (optional, set env vars to enable):
#   NOTIFY_GITHUB_ISSUE=owner/repo    Create/update a GitHub issue on drift
#   NOTIFY_SLACK_WEBHOOK=https://...   Post to Slack webhook on drift
#   NOTIFY_FILE=/path/to/drift.md      Write drift report to a file
#
# Requires:
#   - gh (GitHub CLI), authenticated
#   - yq (optional, falls back to grep-based parsing)
#   - livedocs + SOURCEGRAPH_ACCESS_TOKEN in ~/.env (for --deep/--semantic)
#   - claude CLI on PATH (for --semantic; uses existing OAuth, no extra API key)

set -euo pipefail

# Source ~/.env for tokens (SOURCEGRAPH_ACCESS_TOKEN, etc.)
# shellcheck disable=SC1090
[[ -f ~/.env ]] && source ~/.env

# Bridge env var name: livedocs expects SRC_ACCESS_TOKEN.
export SRC_ACCESS_TOKEN="${SRC_ACCESS_TOKEN:-${SOURCEGRAPH_ACCESS_TOKEN:-}}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE_DIR="${SCRIPT_DIR}/.state"
DOC_MAP="${SCRIPT_DIR}/doc-map.yaml"
LOG_DIR="${SCRIPT_DIR}/logs"

# owner/repo pairs to monitor
declare -A REPOS=(
  [gastown]="gastownhall/gastown"
  [gascity]="gastownhall/gascity"
  [beads]="gastownhall/beads"
  [dolt]="dolthub/dolt"
)

# ── Helpers ──────────────────────────────────────────────────

die() { echo "ERROR: $*" >&2; exit 1; }
ts()  { date '+%Y-%m-%d %H:%M:%S'; }
log() { echo "[$(ts)] $*"; }

check_prereqs() {
  command -v gh >/dev/null 2>&1 || die "gh (GitHub CLI) not found. Install: https://cli.github.com"
  gh auth status >/dev/null 2>&1 || die "gh not authenticated. Run: gh auth login"
}

# ── Notifications ────────────────────────────────────────────

# Send drift notifications via configured channels.
# Args: $1 = summary text, $2 = doc list (newline-separated)
notify_drift() {
  local summary="$1" doc_list="$2"

  # GitHub Issue: create or update a tracking issue.
  if [[ -n "${NOTIFY_GITHUB_ISSUE:-}" ]]; then
    notify_github_issue "$summary" "$doc_list"
  fi

  # Slack webhook: post a message.
  if [[ -n "${NOTIFY_SLACK_WEBHOOK:-}" ]]; then
    notify_slack "$summary" "$doc_list"
  fi

  # File: write a timestamped report.
  if [[ -n "${NOTIFY_FILE:-}" ]]; then
    notify_file "$summary" "$doc_list"
  fi
}

notify_github_issue() {
  local summary="$1" doc_list="$2"
  local repo="${NOTIFY_GITHUB_ISSUE}"
  local title="docs: documentation drift detected"
  local body
  body="$(cat <<EOF
## Documentation Drift Detected

**$(ts)**

${summary}

### Affected Documents

${doc_list}

---
*Auto-generated by gascity_livedocs poll-repos.sh*
EOF
)"

  # Check if an open issue with this title already exists.
  local existing
  existing=$(gh issue list --repo "$repo" --state open --search "in:title $title" --json number --jq '.[0].number' 2>/dev/null) || true

  if [[ -n "$existing" ]]; then
    # Comment on existing issue.
    gh issue comment "$existing" --repo "$repo" --body "$body" 2>/dev/null && \
      log "  Notification: updated GitHub issue #${existing}" || \
      log "  WARN: failed to update GitHub issue"
  else
    # Create new issue.
    gh issue create --repo "$repo" --title "$title" --body "$body" --label "documentation" 2>/dev/null && \
      log "  Notification: created GitHub issue" || \
      log "  WARN: failed to create GitHub issue"
  fi
}

notify_slack() {
  local summary="$1" doc_list="$2"
  local payload
  payload=$(cat <<EOF
{
  "text": ":warning: *Documentation Drift Detected*\n\n${summary}\n\nAffected docs:\n${doc_list}"
}
EOF
)
  curl -s -X POST -H 'Content-Type: application/json' \
    -d "$payload" "${NOTIFY_SLACK_WEBHOOK}" >/dev/null 2>&1 && \
    log "  Notification: posted to Slack" || \
    log "  WARN: failed to post to Slack"
}

notify_file() {
  local summary="$1" doc_list="$2"
  local report_file="${NOTIFY_FILE}"
  mkdir -p "$(dirname "$report_file")"
  cat >> "$report_file" <<EOF

---
## $(ts)

${summary}

### Affected Documents

${doc_list}
EOF
  log "  Notification: appended to ${report_file}"
}

ensure_dirs() {
  mkdir -p "$STATE_DIR" "$LOG_DIR"
}

# Read the last-seen SHA for a repo. Returns empty string if no state.
read_state() {
  local short="$1"
  local state_file="${STATE_DIR}/${short}.sha"
  if [[ -f "$state_file" ]]; then
    cat "$state_file"
  fi
}

# Write the current SHA for a repo.
write_state() {
  local short="$1" sha="$2"
  echo "$sha" > "${STATE_DIR}/${short}.sha"
}

# ── GitHub API ───────────────────────────────────────────────

# Get the latest commit SHA on main for a repo.
get_head_sha() {
  local owner_repo="$1"
  gh api "repos/${owner_repo}/commits/main" --jq '.sha' 2>/dev/null
}

# Get the list of changed files between two SHAs.
get_changed_files() {
  local owner_repo="$1" old_sha="$2" new_sha="$3"
  gh api "repos/${owner_repo}/compare/${old_sha}...${new_sha}" \
    --jq '.files[].filename' 2>/dev/null
}

# ── Doc-map lookup ───────────────────────────────────────────

# Given a repo short name and a list of changed files, return affected doc paths.
lookup_affected_docs() {
  local short="$1"
  shift
  local -a changed_files=("$@")

  if [[ ${#changed_files[@]} -eq 0 ]]; then
    return
  fi

  # Extract all source patterns and their docs for this repo from doc-map.yaml.
  # We parse the YAML with lightweight text processing to avoid hard yq dependency.
  local in_repo=0
  local current_source=""
  local -A doc_set

  while IFS= read -r line; do
    # Detect repo block start.
    if [[ "$line" =~ ^[[:space:]]*short:[[:space:]]*(.+)$ ]]; then
      local found_short="${BASH_REMATCH[1]}"
      found_short="${found_short%\"}"
      found_short="${found_short#\"}"
      if [[ "$found_short" == "$short" ]]; then
        in_repo=1
      else
        in_repo=0
      fi
      continue
    fi

    [[ "$in_repo" -eq 0 ]] && continue

    # New top-level repo block — stop.
    if [[ "$line" =~ ^[[:space:]]*-[[:space:]]*name: ]]; then
      break
    fi

    # Capture source pattern.
    if [[ "$line" =~ ^[[:space:]]*source:[[:space:]]*\"(.+)\"$ ]] || [[ "$line" =~ ^[[:space:]]*source:[[:space:]]*(.+)$ ]]; then
      current_source="${BASH_REMATCH[1]}"
      current_source="${current_source%\"}"
      current_source="${current_source#\"}"
      continue
    fi

    # Capture doc path.
    if [[ "$line" =~ ^[[:space:]]*-[[:space:]]*(docs/.+\.md)$ ]]; then
      local doc="${BASH_REMATCH[1]}"
      # Check if any changed file matches the current source pattern.
      for cf in "${changed_files[@]}"; do
        if match_glob "$current_source" "$cf"; then
          doc_set["$doc"]=1
          break
        fi
      done
    fi
  done < "$DOC_MAP"

  # Output unique affected docs.
  for doc in $(echo "${!doc_set[@]}" | tr ' ' '\n' | sort); do
    echo "$doc"
  done
}

# Glob match supporting * (single segment) and ** (any depth) patterns.
# Builds a regex character-by-character to avoid replacement ordering issues.
match_glob() {
  local pattern="$1" path="$2"
  local regex=""
  local i=0
  local len=${#pattern}

  while (( i < len )); do
    local c="${pattern:$i:1}"
    local next="${pattern:$((i+1)):1}"
    local after="${pattern:$((i+2)):1}"

    if [[ "$c" == "*" && "$next" == "*" ]]; then
      if [[ "$after" == "/" ]]; then
        # **/ → zero or more path segments
        regex+="(.*/|)"
        (( i += 3 ))
      else
        # ** at end → anything
        regex+=".*"
        (( i += 2 ))
      fi
    elif [[ "$c" == "*" ]]; then
      regex+="[^/]*"
      (( i += 1 ))
    elif [[ "$c" == "." ]]; then
      regex+="\\."
      (( i += 1 ))
    else
      regex+="$c"
      (( i += 1 ))
    fi
  done

  regex="^${regex}$"
  [[ "$path" =~ $regex ]]
}

# ── Deep check (livedocs + Sourcegraph MCP) ──────────────────

run_deep_check() {
  local short="$1" owner_repo="$2"
  local repo_fqn="github.com/${owner_repo}"
  local db_path="${SCRIPT_DIR}/data/${short}.claims.db"
  local livedocs="${LIVEDOCS_BIN:-livedocs}"

  if ! command -v "$livedocs" >/dev/null 2>&1; then
    log "  SKIP deep check: livedocs not found"
    return
  fi
  if [[ -z "${SRC_ACCESS_TOKEN:-}" ]]; then
    log "  SKIP deep check: SRC_ACCESS_TOKEN not set"
    return
  fi

  mkdir -p "${SCRIPT_DIR}/data"

  log "  Running livedocs extraction for ${repo_fqn}..."
  "$livedocs" extract \
    --source sourcegraph \
    --repo "$repo_fqn" \
    -o "$db_path" \
    --concurrency 10 \
    2>&1 | sed 's/^/    /'

  log "  Running drift check..."
  "$livedocs" check \
    --db "$db_path" \
    --docs-dir "${SCRIPT_DIR}/docs" \
    --format json 2>/dev/null | sed 's/^/    /' || true
}

# ── Commands ─────────────────────────────────────────────────

cmd_poll() {
  local deep="${1:-}"
  local any_changes=0
  local -a all_affected_docs=()

  for short in "${!REPOS[@]}"; do
    local owner_repo="${REPOS[$short]}"
    local old_sha new_sha

    log "Checking ${owner_repo}..."

    new_sha=$(get_head_sha "$owner_repo") || {
      log "  WARN: failed to fetch HEAD for ${owner_repo}"
      continue
    }
    old_sha=$(read_state "$short")

    if [[ -z "$old_sha" ]]; then
      log "  First run — recording SHA ${new_sha:0:12} (no diff available)"
      write_state "$short" "$new_sha"
      continue
    fi

    if [[ "$old_sha" == "$new_sha" ]]; then
      log "  No changes (${new_sha:0:12})"
      continue
    fi

    any_changes=1
    log "  NEW COMMITS: ${old_sha:0:12} → ${new_sha:0:12}"

    # Get changed files.
    local -a changed_files=()
    while IFS= read -r f; do
      [[ -n "$f" ]] && changed_files+=("$f")
    done < <(get_changed_files "$owner_repo" "$old_sha" "$new_sha")

    log "  Changed files: ${#changed_files[@]}"

    # Look up affected docs via doc-map.
    if [[ ${#changed_files[@]} -gt 0 ]]; then
      local -a affected=()
      while IFS= read -r doc; do
        [[ -n "$doc" ]] && affected+=("$doc")
      done < <(lookup_affected_docs "$short" "${changed_files[@]}")

      if [[ ${#affected[@]} -gt 0 ]]; then
        log "  Affected documents:"
        for doc in "${affected[@]}"; do
          log "    - ${doc}"
          all_affected_docs+=("$doc")
        done
      else
        log "  No mapped documents affected"
      fi
    fi

    # Run deep structural analysis if requested.
    if [[ "$deep" == "--deep" ]]; then
      run_deep_check "$short" "$owner_repo"
    fi

    # Update state.
    write_state "$short" "$new_sha"
  done

  # Summary.
  echo ""
  if [[ "$any_changes" -eq 1 ]]; then
    # Deduplicate affected docs.
    local -A unique_docs
    for doc in "${all_affected_docs[@]}"; do
      unique_docs["$doc"]=1
    done

    if [[ ${#unique_docs[@]} -gt 0 ]]; then
      log "=== SUMMARY: ${#unique_docs[@]} document(s) may need updating ==="
      local doc_list=""
      for doc in $(echo "${!unique_docs[@]}" | tr ' ' '\n' | sort); do
        log "  - ${doc}"
        doc_list+="- ${doc}\n"
      done

      # Send notifications.
      notify_drift "${#unique_docs[@]} document(s) may need updating" "$(echo -e "$doc_list")"
    else
      log "=== SUMMARY: Changes detected but no mapped documents affected ==="
    fi
    # Run cross-repo semantic check and auto-fix if requested.
    if [[ "$deep" == "--semantic" ]] && [[ ${#unique_docs[@]} -gt 0 ]]; then
      log ""
      log "Running cross-repo semantic check + auto-fix..."
      "${SCRIPT_DIR}/fix-docs.sh" || true
    fi
  else
    log "=== SUMMARY: No new commits on any monitored repo ==="
  fi
}

cmd_status() {
  echo "=== Poll State ==="
  echo ""
  for short in $(echo "${!REPOS[@]}" | tr ' ' '\n' | sort); do
    local owner_repo="${REPOS[$short]}"
    local sha
    sha=$(read_state "$short")
    if [[ -n "$sha" ]]; then
      echo "  ${owner_repo}: ${sha:0:12}"
    else
      echo "  ${owner_repo}: (no state — will initialize on next poll)"
    fi
  done
}

cmd_reset() {
  echo "Clearing poll state..."
  rm -rf "$STATE_DIR"
  mkdir -p "$STATE_DIR"
  echo "Done. Next poll will record current SHAs without diffing."
}

# ── Main ─────────────────────────────────────────────────────

main() {
  check_prereqs
  ensure_dirs

  case "${1:-}" in
    --deep)     cmd_poll --deep ;;
    --semantic) cmd_poll --semantic ;;
    --status)   cmd_status ;;
    --reset)    cmd_reset ;;
    --help|-h)
      head -19 "${BASH_SOURCE[0]}" | tail -17
      ;;
    *)          cmd_poll ;;
  esac
}

main "$@"
