package lang

func pythonConfig() *Config {
	return &Config{
		Language:    "python",
		GrammarName: "tree-sitter-python",
		Extensions:  []string{".py"},
		TestPatterns: []string{
			"test_*.py",
			"*_test.py",
			"tests/*",
			"__tests__/*",
		},
		GeneratedPatterns: []string{
			"^# This file is auto-generated",
			"^# Generated by",
		},
		mappings: map[string]ClaimMapping{
			"function_definition": {
				NodeType:   "function_definition",
				Predicate:  "defines",
				Confidence: 1.0,
				SymbolKind: "func",
			},
			"class_definition": {
				NodeType:   "class_definition",
				Predicate:  "defines",
				Confidence: 1.0,
				SymbolKind: "class",
			},
			"decorated_definition": {
				NodeType:   "decorated_definition",
				Predicate:  "defines",
				Confidence: 1.0,
				SymbolKind: "func", // typically wraps func/class; extractor refines via child
			},
			"import_statement": {
				NodeType:   "import_statement",
				Predicate:  "imports",
				Confidence: 1.0,
			},
			"import_from_statement": {
				NodeType:   "import_from_statement",
				Predicate:  "imports",
				Confidence: 1.0,
			},
			"comment": {
				NodeType:   "comment",
				Predicate:  "has_doc",
				Confidence: 0.85,
			},
			"expression_statement": {
				NodeType:             "expression_statement",
				Predicate:            "has_doc",
				Confidence:           0.85,
				NeedsChildInspection: true, // only when child is a string (docstring)
			},
		},
	}
}
