package lang

func shellConfig() *Config {
	return &Config{
		Language:    "shell",
		GrammarName: "tree-sitter-bash",
		Extensions:  []string{".sh", ".bash"},
		TestPatterns: []string{
			"test_*.sh",
			"*_test.sh",
			"tests/*",
		},
		GeneratedPatterns: []string{
			"^# This file is auto-generated",
			"^# Generated by",
		},
		mappings: map[string]ClaimMapping{
			"function_definition": {
				NodeType:   "function_definition",
				Predicate:  "defines",
				Confidence: 1.0,
				SymbolKind: "func",
			},
			"command": {
				NodeType:             "command",
				Predicate:            "imports",
				Confidence:           1.0,
				NeedsChildInspection: true, // only "source" or "." commands
			},
			"comment": {
				NodeType:   "comment",
				Predicate:  "has_doc",
				Confidence: 0.85,
			},
		},
	}
}
